DROP TABLE IF EXISTS `test_tbl`;

CREATE TABLE IF NOT EXISTS `test_tbl` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `text` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;